import Head from "next/head";
import Hero from "../components/Hero";
import NavBar from "../components/NavBar";
import Options from "../components/Options";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>get it done</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Hero />
      <Options />
      <Footer />
    </div>
  );
}
